error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T07:37:09.597Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T07:46:44.333Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T07:47:35.737Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 36
    at JSON.parse (<anonymous>)
    at parse (D:\projectt\fundo-notes\node_modules\body-parser\lib\types\json.js:89:19)
    at D:\projectt\fundo-notes\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:201:9)
    at invokeCallback (D:\projectt\fundo-notes\node_modules\raw-body\index.js:231:16)
    at done (D:\projectt\fundo-notes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\projectt\fundo-notes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:538:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:05:02.068Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:05:11.552Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:08:40.547Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:17:09.733Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:17:22.170Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:26:33.579Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:27:19.026Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:27:33.509Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T08:58:14.651Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T09:04:21.440Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T09:04:22.904Z"}
error: 
    status - 500 
    message - ValidationError: "firstname" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T11:59:52.734Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: SampleDB_Adesh.users index: email_1 dup key: { email: "barbade123@gmail.com" } 
      url - /api/v1/users 
      method - POST 
      IP - ::1
     {"timestamp":"2022-05-19T12:01:01.981Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (D:\projectt\fundo-notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (D:\projectt\fundo-notes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\projectt\fundo-notes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\projectt\fundo-notes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:326:13)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-19T12:01:01.990Z"}
error: 
    status - 500 
    message - TypeError: UserService.userLogIn is not a function
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:31:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userLogIn (D:\projectt\fundo-notes\src\controllers\/user.controller.js:29:24)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T12:13:26.598Z"}
error: 
    status - 500 
    message - ReferenceError: bcrypt is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:28:10)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T13:13:58.145Z"}
error: 
    status - 500 
    message - TypeError: UserService.userLogIn is not a function
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:31:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userLogIn (D:\projectt\fundo-notes\src\controllers\/user.controller.js:29:24)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T13:45:56.589Z"}
error: 
    status - 500 
    message - Error: User not Registered
    at _callee$ (D:\projectt\fundo-notes\src\services\/user.service.js:21:9)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1//users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T13:55:34.700Z"}
error: 
    status - 500 
    message - ReferenceError: bcrypt is not defined
    at _callee$ (D:\projectt\fundo-notes\src\services\/user.service.js:9:10)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1//users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T13:56:35.038Z"}
error: 
    status - 500 
    message - ReferenceError: bcrypt is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:24:10)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T13:57:54.373Z"}
error: 
    status - 500 
    message - ReferenceError: bcrypt is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:24:10)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T13:59:43.101Z"}
error: 
    status - 500 
    message - ReferenceError: bcrypt is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:24:10)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:00:27.363Z"}
error: 
    status - 500 
    message - TypeError: UserService.userLogIn is not a function
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:31:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userLogIn (D:\projectt\fundo-notes\src\controllers\/user.controller.js:29:24)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:04:07.653Z"}
error: 
    status - 500 
    message - ReferenceError: user is not defined
    at _callee$ (D:\projectt\fundo-notes\src\services\/user.service.js:5:26)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:5:23)
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:31:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:18:18.725Z"}
error: 
    status - 500 
    message - ReferenceError: user is not defined
    at _callee$ (D:\projectt\fundo-notes\src\services\/user.service.js:5:26)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:5:23)
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:31:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:18:40.678Z"}
error: 
    status - 500 
    message - ReferenceError: user is not defined
    at _callee$ (D:\projectt\fundo-notes\src\services\/user.service.js:5:26)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:5:23)
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:31:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:20:56.399Z"}
error: 
    status - 500 
    message - TypeError: UserService.getAllUsers is not a function
    at _callee$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:12:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at getAllUsers (D:\projectt\fundo-notes\src\controllers\/user.controller.js:10:25)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12) 
    url - /api/v1/users/alldata 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:39:51.962Z"}
error: 
    status - 500 
    message - ReferenceError: userBody is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:45)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:50:48.179Z"}
error: 
    status - 500 
    message - ReferenceError: userBody is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:45)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:51:01.573Z"}
error: 
    status - 500 
    message - ReferenceError: userBody is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:45)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:52:16.391Z"}
error: 
    status - 500 
    message - ReferenceError: userBody is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:45)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:52:17.991Z"}
error: 
    status - 500 
    message - ReferenceError: userBody is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:45)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-19T14:52:47.201Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:34)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T01:49:52.768Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:34)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T01:50:04.962Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (D:\projectt\fundo-notes\src\services\/user.service.js:11:34)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogIn (D:\projectt\fundo-notes\src\services\/user.service.js:10:25)
    at _callee3$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:49:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-05-20T01:51:57.899Z"}
error: 
    status - 500 
    message - TypeError: UserService.newUser is not a function
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:30:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userRegistration (D:\projectt\fundo-notes\src\controllers\/user.controller.js:28:31)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:144:13)
    at userRegistrationValidator (D:\projectt\fundo-notes\src\validators\/user.validator.js:15:5)
    at Layer.handle [as handle_request] (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\projectt\fundo-notes\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-20T04:06:24.629Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: SampleDB_Adesh.users index: email_1 dup key: { email: "abcde@gmail.com" } 
      url - /api/v1/users 
      method - POST 
      IP - ::1
     {"timestamp":"2022-05-20T04:13:05.785Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (D:\projectt\fundo-notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (D:\projectt\fundo-notes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\projectt\fundo-notes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\projectt\fundo-notes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\projectt\fundo-notes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:326:13)
    at D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\projectt\fundo-notes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-20T04:13:05.813Z"}
error: 
    status - 500 
    message - ReferenceError: saltRound is not defined
    at _callee3$ (D:\projectt\fundo-notes\src\services\/user.service.js:29:38)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.newUser (D:\projectt\fundo-notes\src\services\/user.service.js:16:21)
    at _callee2$ (D:\projectt\fundo-notes\src\controllers\/user.controller.js:30:36)
    at tryCatch (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (D:\projectt\fundo-notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\projectt\fundo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-20T04:33:58.944Z"}
